# Generated by Django 6.0.2 on 2026-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('commission_type', models.CharField(choices=[('character', 'Character'), ('environment', 'Environment'), ('prop', 'Props and Assets'), ('other', 'Other')], default='character', max_length=50)),
                ('budget', models.CharField(help_text='e.g. 5000 to 10000', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='commissions/refs/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
