# Generated by Django 6.0.2 on 2026-02-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('environment', 'Environment'), ('character', 'Character'), ('prop', 'Props and Assets')], default='environment', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('icon', models.CharField(default='fa-solid fa-cube', help_text='Font Awesome class e.g. fa-solid fa-mountain-sun', max_length=100)),
                ('gradient', models.CharField(choices=[('env-gradient', 'Environment Gradient'), ('char-gradient', 'Character Gradient'), ('prop-gradient', 'Prop Gradient')], default='env-gradient', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='portfolio.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
